//#line 2 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the asctec_hl_interface package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __asctec_hl_interface__HLINTERFACECONFIG_H__
#define __asctec_hl_interface__HLINTERFACECONFIG_H__

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace asctec_hl_interface
{
  class HLInterfaceConfigStatics;

  class HLInterfaceConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }

      virtual void clamp(HLInterfaceConfig &config, const HLInterfaceConfig &max, const HLInterfaceConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const HLInterfaceConfig &config1, const HLInterfaceConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, HLInterfaceConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const HLInterfaceConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, HLInterfaceConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const HLInterfaceConfig &config) const = 0;
      virtual void getValue(const HLInterfaceConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    template <class T>
    class ParamDescription : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T HLInterfaceConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T (HLInterfaceConfig::* field);

      virtual void clamp(HLInterfaceConfig &config, const HLInterfaceConfig &max, const HLInterfaceConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const HLInterfaceConfig &config1, const HLInterfaceConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, HLInterfaceConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const HLInterfaceConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, HLInterfaceConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const HLInterfaceConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const HLInterfaceConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, HLInterfaceConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    template<class T, class PT>
    class GroupDescription : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, HLInterfaceConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<HLInterfaceConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(HLInterfaceConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("packet_rate_imu"==(*_i)->name){packet_rate_imu = boost::any_cast<double>(val);}
        if("packet_rate_rc"==(*_i)->name){packet_rate_rc = boost::any_cast<double>(val);}
        if("packet_rate_gps"==(*_i)->name){packet_rate_gps = boost::any_cast<double>(val);}
        if("packet_rate_ssdk_debug"==(*_i)->name){packet_rate_ssdk_debug = boost::any_cast<double>(val);}
        if("packet_rate_ekf_state"==(*_i)->name){packet_rate_ekf_state = boost::any_cast<double>(val);}
        if("packet_rate_mag"==(*_i)->name){packet_rate_mag = boost::any_cast<double>(val);}
        if("battery_warning"==(*_i)->name){battery_warning = boost::any_cast<double>(val);}
        if("enable_x"==(*_i)->name){enable_x = boost::any_cast<bool>(val);}
        if("enable_y"==(*_i)->name){enable_y = boost::any_cast<bool>(val);}
        if("enable_z"==(*_i)->name){enable_z = boost::any_cast<bool>(val);}
        if("enable_yaw"==(*_i)->name){enable_yaw = boost::any_cast<bool>(val);}
        if("position_control"==(*_i)->name){position_control = boost::any_cast<std::string>(val);}
        if("state_estimation"==(*_i)->name){state_estimation = boost::any_cast<std::string>(val);}
        if("max_velocity_xy"==(*_i)->name){max_velocity_xy = boost::any_cast<double>(val);}
        if("max_velocity_z"==(*_i)->name){max_velocity_z = boost::any_cast<double>(val);}
        if("max_velocity_yaw"==(*_i)->name){max_velocity_yaw = boost::any_cast<double>(val);}
        if("min_pos_x"==(*_i)->name){min_pos_x = boost::any_cast<double>(val);}
        if("min_pos_y"==(*_i)->name){min_pos_y = boost::any_cast<double>(val);}
        if("min_pos_z"==(*_i)->name){min_pos_z = boost::any_cast<double>(val);}
        if("max_pos_x"==(*_i)->name){max_pos_x = boost::any_cast<double>(val);}
        if("max_pos_y"==(*_i)->name){max_pos_y = boost::any_cast<double>(val);}
        if("max_pos_z"==(*_i)->name){max_pos_z = boost::any_cast<double>(val);}
      }
    }

    double packet_rate_imu;
double packet_rate_rc;
double packet_rate_gps;
double packet_rate_ssdk_debug;
double packet_rate_ekf_state;
double packet_rate_mag;
double battery_warning;
bool enable_x;
bool enable_y;
bool enable_z;
bool enable_yaw;
std::string position_control;
std::string state_estimation;
double max_velocity_xy;
double max_velocity_z;
double max_velocity_yaw;
double min_pos_x;
double min_pos_y;
double min_pos_z;
double max_pos_x;
double max_pos_y;
double max_pos_z;

    bool state;
    std::string name;

    
}groups;



//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double packet_rate_imu;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double packet_rate_rc;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double packet_rate_gps;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double packet_rate_ssdk_debug;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double packet_rate_ekf_state;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double packet_rate_mag;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double battery_warning;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool enable_x;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool enable_y;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool enable_z;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool enable_yaw;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      std::string position_control;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      std::string state_estimation;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double max_velocity_xy;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double max_velocity_z;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double max_velocity_yaw;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double min_pos_x;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double min_pos_y;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double min_pos_z;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double max_pos_x;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double max_pos_y;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double max_pos_z;
//#line 218 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("HLInterfaceConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const HLInterfaceConfig &__max__ = __getMax__();
      const HLInterfaceConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const HLInterfaceConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const HLInterfaceConfig &__getDefault__();
    static const HLInterfaceConfig &__getMax__();
    static const HLInterfaceConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const HLInterfaceConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void HLInterfaceConfig::ParamDescription<std::string>::clamp(HLInterfaceConfig &config, const HLInterfaceConfig &max, const HLInterfaceConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class HLInterfaceConfigStatics
  {
    friend class HLInterfaceConfig;

    HLInterfaceConfigStatics()
    {
HLInterfaceConfig::GroupDescription<HLInterfaceConfig::DEFAULT, HLInterfaceConfig> Default("Default", "", 0, 0, true, &HLInterfaceConfig::groups);
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.packet_rate_imu = 0.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.packet_rate_imu = 1000.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.packet_rate_imu = 50.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(HLInterfaceConfig::AbstractParamDescriptionConstPtr(new HLInterfaceConfig::ParamDescription<double>("packet_rate_imu", "double", 2, "configures packet rate [Hz] of imu packet.", "", &HLInterfaceConfig::packet_rate_imu)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(HLInterfaceConfig::AbstractParamDescriptionConstPtr(new HLInterfaceConfig::ParamDescription<double>("packet_rate_imu", "double", 2, "configures packet rate [Hz] of imu packet.", "", &HLInterfaceConfig::packet_rate_imu)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.packet_rate_rc = 0.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.packet_rate_rc = 1000.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.packet_rate_rc = 10.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(HLInterfaceConfig::AbstractParamDescriptionConstPtr(new HLInterfaceConfig::ParamDescription<double>("packet_rate_rc", "double", 2, "configures packet rate [Hz] of rc packet.", "", &HLInterfaceConfig::packet_rate_rc)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(HLInterfaceConfig::AbstractParamDescriptionConstPtr(new HLInterfaceConfig::ParamDescription<double>("packet_rate_rc", "double", 2, "configures packet rate [Hz] of rc packet.", "", &HLInterfaceConfig::packet_rate_rc)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.packet_rate_gps = 0.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.packet_rate_gps = 1000.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.packet_rate_gps = 5.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(HLInterfaceConfig::AbstractParamDescriptionConstPtr(new HLInterfaceConfig::ParamDescription<double>("packet_rate_gps", "double", 2, "configures packet rate [Hz] of gps packet.", "", &HLInterfaceConfig::packet_rate_gps)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(HLInterfaceConfig::AbstractParamDescriptionConstPtr(new HLInterfaceConfig::ParamDescription<double>("packet_rate_gps", "double", 2, "configures packet rate [Hz] of gps packet.", "", &HLInterfaceConfig::packet_rate_gps)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.packet_rate_ssdk_debug = 0.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.packet_rate_ssdk_debug = 1000.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.packet_rate_ssdk_debug = 5.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(HLInterfaceConfig::AbstractParamDescriptionConstPtr(new HLInterfaceConfig::ParamDescription<double>("packet_rate_ssdk_debug", "double", 2, "configures packet rate [Hz] of ssdk debug packet.", "", &HLInterfaceConfig::packet_rate_ssdk_debug)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(HLInterfaceConfig::AbstractParamDescriptionConstPtr(new HLInterfaceConfig::ParamDescription<double>("packet_rate_ssdk_debug", "double", 2, "configures packet rate [Hz] of ssdk debug packet.", "", &HLInterfaceConfig::packet_rate_ssdk_debug)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.packet_rate_ekf_state = 0.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.packet_rate_ekf_state = 1000.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.packet_rate_ekf_state = 0.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(HLInterfaceConfig::AbstractParamDescriptionConstPtr(new HLInterfaceConfig::ParamDescription<double>("packet_rate_ekf_state", "double", 2, "configures packet rate [Hz] of ekf state packet.", "", &HLInterfaceConfig::packet_rate_ekf_state)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(HLInterfaceConfig::AbstractParamDescriptionConstPtr(new HLInterfaceConfig::ParamDescription<double>("packet_rate_ekf_state", "double", 2, "configures packet rate [Hz] of ekf state packet.", "", &HLInterfaceConfig::packet_rate_ekf_state)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.packet_rate_mag = 0.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.packet_rate_mag = 1000.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.packet_rate_mag = 0.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(HLInterfaceConfig::AbstractParamDescriptionConstPtr(new HLInterfaceConfig::ParamDescription<double>("packet_rate_mag", "double", 2, "configures packet rate [Hz] of magnetic compass packet.", "", &HLInterfaceConfig::packet_rate_mag)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(HLInterfaceConfig::AbstractParamDescriptionConstPtr(new HLInterfaceConfig::ParamDescription<double>("packet_rate_mag", "double", 2, "configures packet rate [Hz] of magnetic compass packet.", "", &HLInterfaceConfig::packet_rate_mag)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.battery_warning = 8.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.battery_warning = 20.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.battery_warning = 9.8;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(HLInterfaceConfig::AbstractParamDescriptionConstPtr(new HLInterfaceConfig::ParamDescription<double>("battery_warning", "double", 4, "Sets the battery warning voltage.", "", &HLInterfaceConfig::battery_warning)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(HLInterfaceConfig::AbstractParamDescriptionConstPtr(new HLInterfaceConfig::ParamDescription<double>("battery_warning", "double", 4, "Sets the battery warning voltage.", "", &HLInterfaceConfig::battery_warning)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.enable_x = 0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.enable_x = 1;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.enable_x = 1;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(HLInterfaceConfig::AbstractParamDescriptionConstPtr(new HLInterfaceConfig::ParamDescription<bool>("enable_x", "bool", 4, "enables x-control. ", "", &HLInterfaceConfig::enable_x)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(HLInterfaceConfig::AbstractParamDescriptionConstPtr(new HLInterfaceConfig::ParamDescription<bool>("enable_x", "bool", 4, "enables x-control. ", "", &HLInterfaceConfig::enable_x)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.enable_y = 0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.enable_y = 1;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.enable_y = 1;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(HLInterfaceConfig::AbstractParamDescriptionConstPtr(new HLInterfaceConfig::ParamDescription<bool>("enable_y", "bool", 4, "enables y-control. ", "", &HLInterfaceConfig::enable_y)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(HLInterfaceConfig::AbstractParamDescriptionConstPtr(new HLInterfaceConfig::ParamDescription<bool>("enable_y", "bool", 4, "enables y-control. ", "", &HLInterfaceConfig::enable_y)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.enable_z = 0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.enable_z = 1;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.enable_z = 1;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(HLInterfaceConfig::AbstractParamDescriptionConstPtr(new HLInterfaceConfig::ParamDescription<bool>("enable_z", "bool", 4, "enables z-control. ", "", &HLInterfaceConfig::enable_z)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(HLInterfaceConfig::AbstractParamDescriptionConstPtr(new HLInterfaceConfig::ParamDescription<bool>("enable_z", "bool", 4, "enables z-control. ", "", &HLInterfaceConfig::enable_z)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.enable_yaw = 0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.enable_yaw = 1;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.enable_yaw = 1;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(HLInterfaceConfig::AbstractParamDescriptionConstPtr(new HLInterfaceConfig::ParamDescription<bool>("enable_yaw", "bool", 4, "enables yaw-control. ", "", &HLInterfaceConfig::enable_yaw)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(HLInterfaceConfig::AbstractParamDescriptionConstPtr(new HLInterfaceConfig::ParamDescription<bool>("enable_yaw", "bool", 4, "enables yaw-control. ", "", &HLInterfaceConfig::enable_yaw)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.position_control = "";
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.position_control = "";
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.position_control = "off";
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(HLInterfaceConfig::AbstractParamDescriptionConstPtr(new HLInterfaceConfig::ParamDescription<std::string>("position_control", "str", 4, "Enables position control either on the HLP or GPS based position control on the LLP.", "{'enum_description': 'An enum to set the position control mode.', 'enum': [{'srcline': 48, 'description': 'position control off', 'srcfile': '/home/mourams/hexv_ctl/src/asctec_mav_framework/asctec_hl_interface/cfg/HLInterface.cfg', 'cconsttype': 'const char * const', 'value': 'off', 'ctype': 'std::string', 'type': 'str', 'name': 'POSCTRL_OFF'}, {'srcline': 49, 'description': 'position control runs on the HLP.', 'srcfile': '/home/mourams/hexv_ctl/src/asctec_mav_framework/asctec_hl_interface/cfg/HLInterface.cfg', 'cconsttype': 'const char * const', 'value': 'HighLevel', 'ctype': 'std::string', 'type': 'str', 'name': 'POSCTRL_HIGHLEVEL'}, {'srcline': 50, 'description': 'gps position control on the LLP.', 'srcfile': '/home/mourams/hexv_ctl/src/asctec_mav_framework/asctec_hl_interface/cfg/HLInterface.cfg', 'cconsttype': 'const char * const', 'value': 'GPS', 'ctype': 'std::string', 'type': 'str', 'name': 'POSCTRL_GPS'}]}", &HLInterfaceConfig::position_control)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(HLInterfaceConfig::AbstractParamDescriptionConstPtr(new HLInterfaceConfig::ParamDescription<std::string>("position_control", "str", 4, "Enables position control either on the HLP or GPS based position control on the LLP.", "{'enum_description': 'An enum to set the position control mode.', 'enum': [{'srcline': 48, 'description': 'position control off', 'srcfile': '/home/mourams/hexv_ctl/src/asctec_mav_framework/asctec_hl_interface/cfg/HLInterface.cfg', 'cconsttype': 'const char * const', 'value': 'off', 'ctype': 'std::string', 'type': 'str', 'name': 'POSCTRL_OFF'}, {'srcline': 49, 'description': 'position control runs on the HLP.', 'srcfile': '/home/mourams/hexv_ctl/src/asctec_mav_framework/asctec_hl_interface/cfg/HLInterface.cfg', 'cconsttype': 'const char * const', 'value': 'HighLevel', 'ctype': 'std::string', 'type': 'str', 'name': 'POSCTRL_HIGHLEVEL'}, {'srcline': 50, 'description': 'gps position control on the LLP.', 'srcfile': '/home/mourams/hexv_ctl/src/asctec_mav_framework/asctec_hl_interface/cfg/HLInterface.cfg', 'cconsttype': 'const char * const', 'value': 'GPS', 'ctype': 'std::string', 'type': 'str', 'name': 'POSCTRL_GPS'}]}", &HLInterfaceConfig::position_control)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.state_estimation = "";
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.state_estimation = "";
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.state_estimation = "off";
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(HLInterfaceConfig::AbstractParamDescriptionConstPtr(new HLInterfaceConfig::ParamDescription<std::string>("state_estimation", "str", 4, "Determines where state estimation is performed.", "{'enum_description': 'An enum to set the state estimation mode.', 'enum': [{'srcline': 54, 'description': 'state estimation off', 'srcfile': '/home/mourams/hexv_ctl/src/asctec_mav_framework/asctec_hl_interface/cfg/HLInterface.cfg', 'cconsttype': 'const char * const', 'value': 'off', 'ctype': 'std::string', 'type': 'str', 'name': 'STATE_EST_OFF'}, {'srcline': 55, 'description': 'state estimation runs on the HLP within the SSDK.', 'srcfile': '/home/mourams/hexv_ctl/src/asctec_mav_framework/asctec_hl_interface/cfg/HLInterface.cfg', 'cconsttype': 'const char * const', 'value': 'HighLevel_SSDK', 'ctype': 'std::string', 'type': 'str', 'name': 'STATE_EST_HIGHLEVEL_SSDK'}, {'srcline': 56, 'description': 'state estimation runs on the HLP within an EKF.', 'srcfile': '/home/mourams/hexv_ctl/src/asctec_mav_framework/asctec_hl_interface/cfg/HLInterface.cfg', 'cconsttype': 'const char * const', 'value': 'HighLevel_EKF', 'ctype': 'std::string', 'type': 'str', 'name': 'STATE_EST_HIGHLEVEL_EKF'}, {'srcline': 57, 'description': 'state estimation is performed externally.', 'srcfile': '/home/mourams/hexv_ctl/src/asctec_mav_framework/asctec_hl_interface/cfg/HLInterface.cfg', 'cconsttype': 'const char * const', 'value': 'Extern', 'ctype': 'std::string', 'type': 'str', 'name': 'STATE_EST_EXTERN'}]}", &HLInterfaceConfig::state_estimation)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(HLInterfaceConfig::AbstractParamDescriptionConstPtr(new HLInterfaceConfig::ParamDescription<std::string>("state_estimation", "str", 4, "Determines where state estimation is performed.", "{'enum_description': 'An enum to set the state estimation mode.', 'enum': [{'srcline': 54, 'description': 'state estimation off', 'srcfile': '/home/mourams/hexv_ctl/src/asctec_mav_framework/asctec_hl_interface/cfg/HLInterface.cfg', 'cconsttype': 'const char * const', 'value': 'off', 'ctype': 'std::string', 'type': 'str', 'name': 'STATE_EST_OFF'}, {'srcline': 55, 'description': 'state estimation runs on the HLP within the SSDK.', 'srcfile': '/home/mourams/hexv_ctl/src/asctec_mav_framework/asctec_hl_interface/cfg/HLInterface.cfg', 'cconsttype': 'const char * const', 'value': 'HighLevel_SSDK', 'ctype': 'std::string', 'type': 'str', 'name': 'STATE_EST_HIGHLEVEL_SSDK'}, {'srcline': 56, 'description': 'state estimation runs on the HLP within an EKF.', 'srcfile': '/home/mourams/hexv_ctl/src/asctec_mav_framework/asctec_hl_interface/cfg/HLInterface.cfg', 'cconsttype': 'const char * const', 'value': 'HighLevel_EKF', 'ctype': 'std::string', 'type': 'str', 'name': 'STATE_EST_HIGHLEVEL_EKF'}, {'srcline': 57, 'description': 'state estimation is performed externally.', 'srcfile': '/home/mourams/hexv_ctl/src/asctec_mav_framework/asctec_hl_interface/cfg/HLInterface.cfg', 'cconsttype': 'const char * const', 'value': 'Extern', 'ctype': 'std::string', 'type': 'str', 'name': 'STATE_EST_EXTERN'}]}", &HLInterfaceConfig::state_estimation)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.max_velocity_xy = 0.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.max_velocity_xy = 10.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.max_velocity_xy = 0.5;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(HLInterfaceConfig::AbstractParamDescriptionConstPtr(new HLInterfaceConfig::ParamDescription<double>("max_velocity_xy", "double", 16777216, "maximum velocity in x/y [m/s].", "", &HLInterfaceConfig::max_velocity_xy)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(HLInterfaceConfig::AbstractParamDescriptionConstPtr(new HLInterfaceConfig::ParamDescription<double>("max_velocity_xy", "double", 16777216, "maximum velocity in x/y [m/s].", "", &HLInterfaceConfig::max_velocity_xy)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.max_velocity_z = 0.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.max_velocity_z = 2.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.max_velocity_z = 0.5;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(HLInterfaceConfig::AbstractParamDescriptionConstPtr(new HLInterfaceConfig::ParamDescription<double>("max_velocity_z", "double", 16777216, "maximum velocity in z [m/s].", "", &HLInterfaceConfig::max_velocity_z)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(HLInterfaceConfig::AbstractParamDescriptionConstPtr(new HLInterfaceConfig::ParamDescription<double>("max_velocity_z", "double", 16777216, "maximum velocity in z [m/s].", "", &HLInterfaceConfig::max_velocity_z)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.max_velocity_yaw = 0.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.max_velocity_yaw = 1.57;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.max_velocity_yaw = 0.1;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(HLInterfaceConfig::AbstractParamDescriptionConstPtr(new HLInterfaceConfig::ParamDescription<double>("max_velocity_yaw", "double", 16777216, "maximum velocity yaw [rad/s].", "", &HLInterfaceConfig::max_velocity_yaw)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(HLInterfaceConfig::AbstractParamDescriptionConstPtr(new HLInterfaceConfig::ParamDescription<double>("max_velocity_yaw", "double", 16777216, "maximum velocity yaw [rad/s].", "", &HLInterfaceConfig::max_velocity_yaw)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.min_pos_x = -1000.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.min_pos_x = 1000.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.min_pos_x = -1000.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(HLInterfaceConfig::AbstractParamDescriptionConstPtr(new HLInterfaceConfig::ParamDescription<double>("min_pos_x", "double", 16777216, "lower bound for position x [m].", "", &HLInterfaceConfig::min_pos_x)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(HLInterfaceConfig::AbstractParamDescriptionConstPtr(new HLInterfaceConfig::ParamDescription<double>("min_pos_x", "double", 16777216, "lower bound for position x [m].", "", &HLInterfaceConfig::min_pos_x)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.min_pos_y = -1000.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.min_pos_y = 1000.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.min_pos_y = -1000.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(HLInterfaceConfig::AbstractParamDescriptionConstPtr(new HLInterfaceConfig::ParamDescription<double>("min_pos_y", "double", 16777216, "lower bound for position y [m].", "", &HLInterfaceConfig::min_pos_y)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(HLInterfaceConfig::AbstractParamDescriptionConstPtr(new HLInterfaceConfig::ParamDescription<double>("min_pos_y", "double", 16777216, "lower bound for position y [m].", "", &HLInterfaceConfig::min_pos_y)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.min_pos_z = -1000.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.min_pos_z = 1000.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.min_pos_z = -1000.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(HLInterfaceConfig::AbstractParamDescriptionConstPtr(new HLInterfaceConfig::ParamDescription<double>("min_pos_z", "double", 16777216, "lower bound for position z [m].", "", &HLInterfaceConfig::min_pos_z)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(HLInterfaceConfig::AbstractParamDescriptionConstPtr(new HLInterfaceConfig::ParamDescription<double>("min_pos_z", "double", 16777216, "lower bound for position z [m].", "", &HLInterfaceConfig::min_pos_z)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.max_pos_x = -1000.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.max_pos_x = 1000.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.max_pos_x = 1000.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(HLInterfaceConfig::AbstractParamDescriptionConstPtr(new HLInterfaceConfig::ParamDescription<double>("max_pos_x", "double", 16777216, "upper bound for position x [m].", "", &HLInterfaceConfig::max_pos_x)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(HLInterfaceConfig::AbstractParamDescriptionConstPtr(new HLInterfaceConfig::ParamDescription<double>("max_pos_x", "double", 16777216, "upper bound for position x [m].", "", &HLInterfaceConfig::max_pos_x)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.max_pos_y = -1000.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.max_pos_y = 1000.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.max_pos_y = 1000.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(HLInterfaceConfig::AbstractParamDescriptionConstPtr(new HLInterfaceConfig::ParamDescription<double>("max_pos_y", "double", 16777216, "upper bound for position y [m].", "", &HLInterfaceConfig::max_pos_y)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(HLInterfaceConfig::AbstractParamDescriptionConstPtr(new HLInterfaceConfig::ParamDescription<double>("max_pos_y", "double", 16777216, "upper bound for position y [m].", "", &HLInterfaceConfig::max_pos_y)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.max_pos_z = -1000.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.max_pos_z = 1000.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.max_pos_z = 1000.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(HLInterfaceConfig::AbstractParamDescriptionConstPtr(new HLInterfaceConfig::ParamDescription<double>("max_pos_z", "double", 16777216, "upper bound for position z [m].", "", &HLInterfaceConfig::max_pos_z)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(HLInterfaceConfig::AbstractParamDescriptionConstPtr(new HLInterfaceConfig::ParamDescription<double>("max_pos_z", "double", 16777216, "upper bound for position z [m].", "", &HLInterfaceConfig::max_pos_z)));
//#line 245 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 245 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(HLInterfaceConfig::AbstractGroupDescriptionConstPtr(new HLInterfaceConfig::GroupDescription<HLInterfaceConfig::DEFAULT, HLInterfaceConfig>(Default)));
//#line 356 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<HLInterfaceConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<HLInterfaceConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<HLInterfaceConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    HLInterfaceConfig __max__;
    HLInterfaceConfig __min__;
    HLInterfaceConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const HLInterfaceConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static HLInterfaceConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &HLInterfaceConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const HLInterfaceConfig &HLInterfaceConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const HLInterfaceConfig &HLInterfaceConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const HLInterfaceConfig &HLInterfaceConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<HLInterfaceConfig::AbstractParamDescriptionConstPtr> &HLInterfaceConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<HLInterfaceConfig::AbstractGroupDescriptionConstPtr> &HLInterfaceConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const HLInterfaceConfigStatics *HLInterfaceConfig::__get_statics__()
  {
    const static HLInterfaceConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = HLInterfaceConfigStatics::get_instance();

    return statics;
  }

//#line 41 "/home/mourams/hexv_ctl/src/asctec_mav_framework/asctec_hl_interface/cfg/HLInterface.cfg"
      const int HLInterface_ENABLE_CTRL = 1;
//#line 42 "/home/mourams/hexv_ctl/src/asctec_mav_framework/asctec_hl_interface/cfg/HLInterface.cfg"
      const int HLInterface_PACKET_RATE = 2;
//#line 43 "/home/mourams/hexv_ctl/src/asctec_mav_framework/asctec_hl_interface/cfg/HLInterface.cfg"
      const int HLInterface_HLI_CONFIG = 4;
//#line 44 "/home/mourams/hexv_ctl/src/asctec_mav_framework/asctec_hl_interface/cfg/HLInterface.cfg"
      const int HLInterface_MISC = 16777216;
//#line 48 "/home/mourams/hexv_ctl/src/asctec_mav_framework/asctec_hl_interface/cfg/HLInterface.cfg"
      const char * const HLInterface_POSCTRL_OFF = "off";
//#line 49 "/home/mourams/hexv_ctl/src/asctec_mav_framework/asctec_hl_interface/cfg/HLInterface.cfg"
      const char * const HLInterface_POSCTRL_HIGHLEVEL = "HighLevel";
//#line 50 "/home/mourams/hexv_ctl/src/asctec_mav_framework/asctec_hl_interface/cfg/HLInterface.cfg"
      const char * const HLInterface_POSCTRL_GPS = "GPS";
//#line 54 "/home/mourams/hexv_ctl/src/asctec_mav_framework/asctec_hl_interface/cfg/HLInterface.cfg"
      const char * const HLInterface_STATE_EST_OFF = "off";
//#line 55 "/home/mourams/hexv_ctl/src/asctec_mav_framework/asctec_hl_interface/cfg/HLInterface.cfg"
      const char * const HLInterface_STATE_EST_HIGHLEVEL_SSDK = "HighLevel_SSDK";
//#line 56 "/home/mourams/hexv_ctl/src/asctec_mav_framework/asctec_hl_interface/cfg/HLInterface.cfg"
      const char * const HLInterface_STATE_EST_HIGHLEVEL_EKF = "HighLevel_EKF";
//#line 57 "/home/mourams/hexv_ctl/src/asctec_mav_framework/asctec_hl_interface/cfg/HLInterface.cfg"
      const char * const HLInterface_STATE_EST_EXTERN = "Extern";
}

#endif // __HLINTERFACERECONFIGURATOR_H__
