//#line 2 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the asctec_hl_interface package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __asctec_hl_interface__SSDKCONFIG_H__
#define __asctec_hl_interface__SSDKCONFIG_H__

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace asctec_hl_interface
{
  class SSDKConfigStatics;

  class SSDKConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }

      virtual void clamp(SSDKConfig &config, const SSDKConfig &max, const SSDKConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const SSDKConfig &config1, const SSDKConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, SSDKConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const SSDKConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, SSDKConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const SSDKConfig &config) const = 0;
      virtual void getValue(const SSDKConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    template <class T>
    class ParamDescription : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T SSDKConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T (SSDKConfig::* field);

      virtual void clamp(SSDKConfig &config, const SSDKConfig &max, const SSDKConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const SSDKConfig &config1, const SSDKConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, SSDKConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const SSDKConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, SSDKConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const SSDKConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const SSDKConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, SSDKConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    template<class T, class PT>
    class GroupDescription : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, SSDKConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<SSDKConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(SSDKConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("listen_on_tf"==(*_i)->name){listen_on_tf = boost::any_cast<bool>(val);}
        if("tf_ref_frame_id"==(*_i)->name){tf_ref_frame_id = boost::any_cast<std::string>(val);}
        if("tf_tracked_frame_id"==(*_i)->name){tf_tracked_frame_id = boost::any_cast<std::string>(val);}
        if("send"==(*_i)->name){send = boost::any_cast<bool>(val);}
        if("omega_0_xy"==(*_i)->name){omega_0_xy = boost::any_cast<double>(val);}
        if("omega_0_z"==(*_i)->name){omega_0_z = boost::any_cast<double>(val);}
        if("zeta_xy"==(*_i)->name){zeta_xy = boost::any_cast<double>(val);}
        if("zeta_z"==(*_i)->name){zeta_z = boost::any_cast<double>(val);}
        if("p1"==(*_i)->name){p1 = boost::any_cast<double>(val);}
        if("p2"==(*_i)->name){p2 = boost::any_cast<double>(val);}
        if("p3"==(*_i)->name){p3 = boost::any_cast<double>(val);}
        if("p4"==(*_i)->name){p4 = boost::any_cast<double>(val);}
        if("p5"==(*_i)->name){p5 = boost::any_cast<double>(val);}
        if("p6"==(*_i)->name){p6 = boost::any_cast<double>(val);}
        if("p7"==(*_i)->name){p7 = boost::any_cast<double>(val);}
        if("p8"==(*_i)->name){p8 = boost::any_cast<double>(val);}
        if("p9"==(*_i)->name){p9 = boost::any_cast<double>(val);}
        if("p10"==(*_i)->name){p10 = boost::any_cast<double>(val);}
        if("p11"==(*_i)->name){p11 = boost::any_cast<double>(val);}
        if("p12"==(*_i)->name){p12 = boost::any_cast<double>(val);}
        if("p13"==(*_i)->name){p13 = boost::any_cast<double>(val);}
        if("p14"==(*_i)->name){p14 = boost::any_cast<double>(val);}
        if("p15"==(*_i)->name){p15 = boost::any_cast<double>(val);}
        if("p16"==(*_i)->name){p16 = boost::any_cast<double>(val);}
        if("p17"==(*_i)->name){p17 = boost::any_cast<double>(val);}
        if("p18"==(*_i)->name){p18 = boost::any_cast<double>(val);}
        if("p19"==(*_i)->name){p19 = boost::any_cast<double>(val);}
        if("p20"==(*_i)->name){p20 = boost::any_cast<double>(val);}
        if("p21"==(*_i)->name){p21 = boost::any_cast<double>(val);}
        if("p22"==(*_i)->name){p22 = boost::any_cast<double>(val);}
        if("p23"==(*_i)->name){p23 = boost::any_cast<double>(val);}
        if("p24"==(*_i)->name){p24 = boost::any_cast<double>(val);}
        if("p25"==(*_i)->name){p25 = boost::any_cast<double>(val);}
        if("p26"==(*_i)->name){p26 = boost::any_cast<double>(val);}
        if("p27"==(*_i)->name){p27 = boost::any_cast<double>(val);}
        if("p28"==(*_i)->name){p28 = boost::any_cast<double>(val);}
        if("p29"==(*_i)->name){p29 = boost::any_cast<double>(val);}
        if("p30"==(*_i)->name){p30 = boost::any_cast<double>(val);}
        if("p31"==(*_i)->name){p31 = boost::any_cast<double>(val);}
        if("p32"==(*_i)->name){p32 = boost::any_cast<double>(val);}
        if("p33"==(*_i)->name){p33 = boost::any_cast<double>(val);}
        if("p34"==(*_i)->name){p34 = boost::any_cast<double>(val);}
        if("p35"==(*_i)->name){p35 = boost::any_cast<double>(val);}
        if("p36"==(*_i)->name){p36 = boost::any_cast<double>(val);}
        if("p37"==(*_i)->name){p37 = boost::any_cast<double>(val);}
        if("p38"==(*_i)->name){p38 = boost::any_cast<double>(val);}
        if("p39"==(*_i)->name){p39 = boost::any_cast<double>(val);}
        if("p40"==(*_i)->name){p40 = boost::any_cast<double>(val);}
        if("p41"==(*_i)->name){p41 = boost::any_cast<double>(val);}
        if("p42"==(*_i)->name){p42 = boost::any_cast<double>(val);}
        if("p43"==(*_i)->name){p43 = boost::any_cast<double>(val);}
        if("p44"==(*_i)->name){p44 = boost::any_cast<double>(val);}
        if("p45"==(*_i)->name){p45 = boost::any_cast<double>(val);}
        if("p46"==(*_i)->name){p46 = boost::any_cast<double>(val);}
        if("p47"==(*_i)->name){p47 = boost::any_cast<double>(val);}
        if("p48"==(*_i)->name){p48 = boost::any_cast<double>(val);}
        if("p49"==(*_i)->name){p49 = boost::any_cast<double>(val);}
        if("p50"==(*_i)->name){p50 = boost::any_cast<double>(val);}
      }
    }

    bool listen_on_tf;
std::string tf_ref_frame_id;
std::string tf_tracked_frame_id;
bool send;
double omega_0_xy;
double omega_0_z;
double zeta_xy;
double zeta_z;
double p1;
double p2;
double p3;
double p4;
double p5;
double p6;
double p7;
double p8;
double p9;
double p10;
double p11;
double p12;
double p13;
double p14;
double p15;
double p16;
double p17;
double p18;
double p19;
double p20;
double p21;
double p22;
double p23;
double p24;
double p25;
double p26;
double p27;
double p28;
double p29;
double p30;
double p31;
double p32;
double p33;
double p34;
double p35;
double p36;
double p37;
double p38;
double p39;
double p40;
double p41;
double p42;
double p43;
double p44;
double p45;
double p46;
double p47;
double p48;
double p49;
double p50;

    bool state;
    std::string name;

    
}groups;



//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool listen_on_tf;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      std::string tf_ref_frame_id;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      std::string tf_tracked_frame_id;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool send;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double omega_0_xy;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double omega_0_z;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double zeta_xy;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double zeta_z;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double p1;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double p2;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double p3;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double p4;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double p5;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double p6;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double p7;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double p8;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double p9;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double p10;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double p11;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double p12;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double p13;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double p14;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double p15;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double p16;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double p17;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double p18;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double p19;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double p20;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double p21;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double p22;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double p23;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double p24;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double p25;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double p26;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double p27;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double p28;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double p29;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double p30;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double p31;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double p32;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double p33;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double p34;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double p35;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double p36;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double p37;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double p38;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double p39;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double p40;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double p41;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double p42;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double p43;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double p44;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double p45;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double p46;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double p47;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double p48;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double p49;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double p50;
//#line 218 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("SSDKConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const SSDKConfig &__max__ = __getMax__();
      const SSDKConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const SSDKConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const SSDKConfig &__getDefault__();
    static const SSDKConfig &__getMax__();
    static const SSDKConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const SSDKConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void SSDKConfig::ParamDescription<std::string>::clamp(SSDKConfig &config, const SSDKConfig &max, const SSDKConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class SSDKConfigStatics
  {
    friend class SSDKConfig;

    SSDKConfigStatics()
    {
SSDKConfig::GroupDescription<SSDKConfig::DEFAULT, SSDKConfig> Default("Default", "", 0, 0, true, &SSDKConfig::groups);
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.listen_on_tf = 0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.listen_on_tf = 1;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.listen_on_tf = 1;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<bool>("listen_on_tf", "bool", 4, "Enables listening on tf transforms for position updates for the state estimation on the HLP.", "", &SSDKConfig::listen_on_tf)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<bool>("listen_on_tf", "bool", 4, "Enables listening on tf transforms for position updates for the state estimation on the HLP.", "", &SSDKConfig::listen_on_tf)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.tf_ref_frame_id = "";
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.tf_ref_frame_id = "";
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.tf_ref_frame_id = "world";
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<std::string>("tf_ref_frame_id", "str", 4, "tf reference frame.", "", &SSDKConfig::tf_ref_frame_id)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<std::string>("tf_ref_frame_id", "str", 4, "tf reference frame.", "", &SSDKConfig::tf_ref_frame_id)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.tf_tracked_frame_id = "";
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.tf_tracked_frame_id = "";
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.tf_tracked_frame_id = "mav";
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<std::string>("tf_tracked_frame_id", "str", 4, "tf frame of the helicopter.", "", &SSDKConfig::tf_tracked_frame_id)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<std::string>("tf_tracked_frame_id", "str", 4, "tf frame of the helicopter.", "", &SSDKConfig::tf_tracked_frame_id)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.send = 0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.send = 1;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.send = 0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<bool>("send", "bool", 1, "used to send all parameters at once.", "", &SSDKConfig::send)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<bool>("send", "bool", 1, "used to send all parameters at once.", "", &SSDKConfig::send)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.omega_0_xy = -100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.omega_0_xy = 100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.omega_0_xy = 2.5;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("omega_0_xy", "double", 2, "natural frequency of the position controller's reference model for x and y axis.", "", &SSDKConfig::omega_0_xy)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("omega_0_xy", "double", 2, "natural frequency of the position controller's reference model for x and y axis.", "", &SSDKConfig::omega_0_xy)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.omega_0_z = -100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.omega_0_z = 100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.omega_0_z = 8.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("omega_0_z", "double", 2, "natural frequency of the position controller's reference model for the z axis.", "", &SSDKConfig::omega_0_z)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("omega_0_z", "double", 2, "natural frequency of the position controller's reference model for the z axis.", "", &SSDKConfig::omega_0_z)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.zeta_xy = -100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.zeta_xy = 100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.zeta_xy = 1.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("zeta_xy", "double", 2, "damping of the position controller's reference model for x and y axis.", "", &SSDKConfig::zeta_xy)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("zeta_xy", "double", 2, "damping of the position controller's reference model for x and y axis.", "", &SSDKConfig::zeta_xy)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.zeta_z = -100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.zeta_z = 100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.zeta_z = 1.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("zeta_z", "double", 2, "damping of the position controller's reference model for the z axis.", "", &SSDKConfig::zeta_z)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("zeta_z", "double", 2, "damping of the position controller's reference model for the z axis.", "", &SSDKConfig::zeta_z)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.p1 = -100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.p1 = 100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.p1 = 0.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p1", "double", 2, " ", "", &SSDKConfig::p1)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p1", "double", 2, " ", "", &SSDKConfig::p1)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.p2 = -100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.p2 = 100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.p2 = 0.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p2", "double", 2, " ", "", &SSDKConfig::p2)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p2", "double", 2, " ", "", &SSDKConfig::p2)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.p3 = -100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.p3 = 100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.p3 = 0.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p3", "double", 2, " ", "", &SSDKConfig::p3)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p3", "double", 2, " ", "", &SSDKConfig::p3)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.p4 = -100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.p4 = 100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.p4 = 0.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p4", "double", 2, " ", "", &SSDKConfig::p4)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p4", "double", 2, " ", "", &SSDKConfig::p4)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.p5 = -100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.p5 = 100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.p5 = 0.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p5", "double", 2, " ", "", &SSDKConfig::p5)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p5", "double", 2, " ", "", &SSDKConfig::p5)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.p6 = -100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.p6 = 100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.p6 = 0.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p6", "double", 2, " ", "", &SSDKConfig::p6)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p6", "double", 2, " ", "", &SSDKConfig::p6)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.p7 = -100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.p7 = 100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.p7 = 0.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p7", "double", 2, " ", "", &SSDKConfig::p7)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p7", "double", 2, " ", "", &SSDKConfig::p7)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.p8 = -100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.p8 = 100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.p8 = 0.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p8", "double", 2, " ", "", &SSDKConfig::p8)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p8", "double", 2, " ", "", &SSDKConfig::p8)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.p9 = -100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.p9 = 100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.p9 = 0.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p9", "double", 2, " ", "", &SSDKConfig::p9)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p9", "double", 2, " ", "", &SSDKConfig::p9)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.p10 = -100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.p10 = 100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.p10 = 0.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p10", "double", 2, " ", "", &SSDKConfig::p10)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p10", "double", 2, " ", "", &SSDKConfig::p10)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.p11 = -100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.p11 = 100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.p11 = 0.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p11", "double", 2, " ", "", &SSDKConfig::p11)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p11", "double", 2, " ", "", &SSDKConfig::p11)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.p12 = -100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.p12 = 100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.p12 = 0.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p12", "double", 2, " ", "", &SSDKConfig::p12)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p12", "double", 2, " ", "", &SSDKConfig::p12)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.p13 = -100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.p13 = 100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.p13 = 0.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p13", "double", 2, " ", "", &SSDKConfig::p13)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p13", "double", 2, " ", "", &SSDKConfig::p13)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.p14 = -100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.p14 = 100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.p14 = 0.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p14", "double", 2, " ", "", &SSDKConfig::p14)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p14", "double", 2, " ", "", &SSDKConfig::p14)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.p15 = -100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.p15 = 100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.p15 = 0.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p15", "double", 2, " ", "", &SSDKConfig::p15)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p15", "double", 2, " ", "", &SSDKConfig::p15)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.p16 = -100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.p16 = 100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.p16 = 0.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p16", "double", 2, " ", "", &SSDKConfig::p16)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p16", "double", 2, " ", "", &SSDKConfig::p16)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.p17 = -100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.p17 = 100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.p17 = 0.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p17", "double", 2, " ", "", &SSDKConfig::p17)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p17", "double", 2, " ", "", &SSDKConfig::p17)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.p18 = -100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.p18 = 100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.p18 = 0.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p18", "double", 2, " ", "", &SSDKConfig::p18)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p18", "double", 2, " ", "", &SSDKConfig::p18)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.p19 = -100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.p19 = 100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.p19 = 0.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p19", "double", 2, " ", "", &SSDKConfig::p19)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p19", "double", 2, " ", "", &SSDKConfig::p19)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.p20 = -100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.p20 = 100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.p20 = 0.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p20", "double", 2, " ", "", &SSDKConfig::p20)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p20", "double", 2, " ", "", &SSDKConfig::p20)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.p21 = -100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.p21 = 100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.p21 = 0.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p21", "double", 2, " ", "", &SSDKConfig::p21)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p21", "double", 2, " ", "", &SSDKConfig::p21)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.p22 = -100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.p22 = 100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.p22 = 0.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p22", "double", 2, " ", "", &SSDKConfig::p22)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p22", "double", 2, " ", "", &SSDKConfig::p22)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.p23 = -100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.p23 = 100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.p23 = 0.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p23", "double", 2, " ", "", &SSDKConfig::p23)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p23", "double", 2, " ", "", &SSDKConfig::p23)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.p24 = -100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.p24 = 100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.p24 = 0.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p24", "double", 2, " ", "", &SSDKConfig::p24)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p24", "double", 2, " ", "", &SSDKConfig::p24)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.p25 = -100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.p25 = 100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.p25 = 0.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p25", "double", 2, " ", "", &SSDKConfig::p25)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p25", "double", 2, " ", "", &SSDKConfig::p25)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.p26 = -100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.p26 = 100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.p26 = 0.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p26", "double", 2, " ", "", &SSDKConfig::p26)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p26", "double", 2, " ", "", &SSDKConfig::p26)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.p27 = -100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.p27 = 100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.p27 = 0.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p27", "double", 2, " ", "", &SSDKConfig::p27)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p27", "double", 2, " ", "", &SSDKConfig::p27)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.p28 = -100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.p28 = 100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.p28 = 0.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p28", "double", 2, " ", "", &SSDKConfig::p28)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p28", "double", 2, " ", "", &SSDKConfig::p28)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.p29 = -100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.p29 = 100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.p29 = 0.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p29", "double", 2, " ", "", &SSDKConfig::p29)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p29", "double", 2, " ", "", &SSDKConfig::p29)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.p30 = -100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.p30 = 100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.p30 = 0.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p30", "double", 2, " ", "", &SSDKConfig::p30)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p30", "double", 2, " ", "", &SSDKConfig::p30)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.p31 = -100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.p31 = 100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.p31 = 0.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p31", "double", 2, " ", "", &SSDKConfig::p31)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p31", "double", 2, " ", "", &SSDKConfig::p31)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.p32 = -100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.p32 = 100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.p32 = 0.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p32", "double", 2, " ", "", &SSDKConfig::p32)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p32", "double", 2, " ", "", &SSDKConfig::p32)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.p33 = -100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.p33 = 100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.p33 = 0.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p33", "double", 2, " ", "", &SSDKConfig::p33)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p33", "double", 2, " ", "", &SSDKConfig::p33)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.p34 = -100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.p34 = 100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.p34 = 0.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p34", "double", 2, " ", "", &SSDKConfig::p34)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p34", "double", 2, " ", "", &SSDKConfig::p34)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.p35 = -100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.p35 = 100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.p35 = 0.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p35", "double", 2, " ", "", &SSDKConfig::p35)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p35", "double", 2, " ", "", &SSDKConfig::p35)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.p36 = -100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.p36 = 100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.p36 = 0.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p36", "double", 2, " ", "", &SSDKConfig::p36)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p36", "double", 2, " ", "", &SSDKConfig::p36)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.p37 = -100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.p37 = 100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.p37 = 0.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p37", "double", 2, " ", "", &SSDKConfig::p37)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p37", "double", 2, " ", "", &SSDKConfig::p37)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.p38 = -100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.p38 = 100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.p38 = 0.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p38", "double", 2, " ", "", &SSDKConfig::p38)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p38", "double", 2, " ", "", &SSDKConfig::p38)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.p39 = -100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.p39 = 100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.p39 = 0.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p39", "double", 2, " ", "", &SSDKConfig::p39)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p39", "double", 2, " ", "", &SSDKConfig::p39)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.p40 = -100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.p40 = 100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.p40 = 0.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p40", "double", 2, " ", "", &SSDKConfig::p40)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p40", "double", 2, " ", "", &SSDKConfig::p40)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.p41 = -100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.p41 = 100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.p41 = 0.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p41", "double", 2, " ", "", &SSDKConfig::p41)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p41", "double", 2, " ", "", &SSDKConfig::p41)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.p42 = -100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.p42 = 100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.p42 = 0.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p42", "double", 2, " ", "", &SSDKConfig::p42)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p42", "double", 2, " ", "", &SSDKConfig::p42)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.p43 = -100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.p43 = 100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.p43 = 0.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p43", "double", 2, " ", "", &SSDKConfig::p43)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p43", "double", 2, " ", "", &SSDKConfig::p43)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.p44 = -100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.p44 = 100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.p44 = 0.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p44", "double", 2, " ", "", &SSDKConfig::p44)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p44", "double", 2, " ", "", &SSDKConfig::p44)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.p45 = -100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.p45 = 100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.p45 = 0.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p45", "double", 2, " ", "", &SSDKConfig::p45)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p45", "double", 2, " ", "", &SSDKConfig::p45)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.p46 = -100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.p46 = 100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.p46 = 0.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p46", "double", 2, " ", "", &SSDKConfig::p46)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p46", "double", 2, " ", "", &SSDKConfig::p46)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.p47 = -100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.p47 = 100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.p47 = 0.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p47", "double", 2, " ", "", &SSDKConfig::p47)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p47", "double", 2, " ", "", &SSDKConfig::p47)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.p48 = -100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.p48 = 100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.p48 = 0.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p48", "double", 2, " ", "", &SSDKConfig::p48)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p48", "double", 2, " ", "", &SSDKConfig::p48)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.p49 = -100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.p49 = 100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.p49 = 0.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p49", "double", 2, " ", "", &SSDKConfig::p49)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p49", "double", 2, " ", "", &SSDKConfig::p49)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.p50 = -100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.p50 = 100.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.p50 = 0.0;
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p50", "double", 2, " ", "", &SSDKConfig::p50)));
//#line 292 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(SSDKConfig::AbstractParamDescriptionConstPtr(new SSDKConfig::ParamDescription<double>("p50", "double", 2, " ", "", &SSDKConfig::p50)));
//#line 245 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 245 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(SSDKConfig::AbstractGroupDescriptionConstPtr(new SSDKConfig::GroupDescription<SSDKConfig::DEFAULT, SSDKConfig>(Default)));
//#line 356 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<SSDKConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<SSDKConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<SSDKConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    SSDKConfig __max__;
    SSDKConfig __min__;
    SSDKConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const SSDKConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static SSDKConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &SSDKConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const SSDKConfig &SSDKConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const SSDKConfig &SSDKConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const SSDKConfig &SSDKConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<SSDKConfig::AbstractParamDescriptionConstPtr> &SSDKConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<SSDKConfig::AbstractGroupDescriptionConstPtr> &SSDKConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const SSDKConfigStatics *SSDKConfig::__get_statics__()
  {
    const static SSDKConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = SSDKConfigStatics::get_instance();

    return statics;
  }

//#line 42 "/home/mourams/hexv_ctl/src/asctec_mav_framework/asctec_hl_interface/cfg/SSDK.cfg"
      const int SSDK_SEND_PARAMETERS = 1;
//#line 43 "/home/mourams/hexv_ctl/src/asctec_mav_framework/asctec_hl_interface/cfg/SSDK.cfg"
      const int SSDK_PARAMETER_CHANGED = 2;
//#line 44 "/home/mourams/hexv_ctl/src/asctec_mav_framework/asctec_hl_interface/cfg/SSDK.cfg"
      const int SSDK_TF_CHANGED = 4;
}

#endif // __SSDKRECONFIGURATOR_H__
