// Auto-generated. Do not edit!

// (in-package asctec_hl_comm.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let geometry_msgs = _finder('geometry_msgs');
let std_msgs = _finder('std_msgs');

//-----------------------------------------------------------

class WaypointGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.header = null;
      this.goal_pos = null;
      this.goal_yaw = null;
      this.max_speed = null;
      this.accuracy_position = null;
      this.accuracy_orientation = null;
      this.timeout = null;
    }
    else {
      if (initObj.hasOwnProperty('header')) {
        this.header = initObj.header
      }
      else {
        this.header = new std_msgs.msg.Header();
      }
      if (initObj.hasOwnProperty('goal_pos')) {
        this.goal_pos = initObj.goal_pos
      }
      else {
        this.goal_pos = new geometry_msgs.msg.Point32();
      }
      if (initObj.hasOwnProperty('goal_yaw')) {
        this.goal_yaw = initObj.goal_yaw
      }
      else {
        this.goal_yaw = 0.0;
      }
      if (initObj.hasOwnProperty('max_speed')) {
        this.max_speed = initObj.max_speed
      }
      else {
        this.max_speed = new geometry_msgs.msg.Point32();
      }
      if (initObj.hasOwnProperty('accuracy_position')) {
        this.accuracy_position = initObj.accuracy_position
      }
      else {
        this.accuracy_position = 0.0;
      }
      if (initObj.hasOwnProperty('accuracy_orientation')) {
        this.accuracy_orientation = initObj.accuracy_orientation
      }
      else {
        this.accuracy_orientation = 0.0;
      }
      if (initObj.hasOwnProperty('timeout')) {
        this.timeout = initObj.timeout
      }
      else {
        this.timeout = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type WaypointGoal
    // Serialize message field [header]
    bufferOffset = std_msgs.msg.Header.serialize(obj.header, buffer, bufferOffset);
    // Serialize message field [goal_pos]
    bufferOffset = geometry_msgs.msg.Point32.serialize(obj.goal_pos, buffer, bufferOffset);
    // Serialize message field [goal_yaw]
    bufferOffset = _serializer.float32(obj.goal_yaw, buffer, bufferOffset);
    // Serialize message field [max_speed]
    bufferOffset = geometry_msgs.msg.Point32.serialize(obj.max_speed, buffer, bufferOffset);
    // Serialize message field [accuracy_position]
    bufferOffset = _serializer.float32(obj.accuracy_position, buffer, bufferOffset);
    // Serialize message field [accuracy_orientation]
    bufferOffset = _serializer.float32(obj.accuracy_orientation, buffer, bufferOffset);
    // Serialize message field [timeout]
    bufferOffset = _serializer.float32(obj.timeout, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type WaypointGoal
    let len;
    let data = new WaypointGoal(null);
    // Deserialize message field [header]
    data.header = std_msgs.msg.Header.deserialize(buffer, bufferOffset);
    // Deserialize message field [goal_pos]
    data.goal_pos = geometry_msgs.msg.Point32.deserialize(buffer, bufferOffset);
    // Deserialize message field [goal_yaw]
    data.goal_yaw = _deserializer.float32(buffer, bufferOffset);
    // Deserialize message field [max_speed]
    data.max_speed = geometry_msgs.msg.Point32.deserialize(buffer, bufferOffset);
    // Deserialize message field [accuracy_position]
    data.accuracy_position = _deserializer.float32(buffer, bufferOffset);
    // Deserialize message field [accuracy_orientation]
    data.accuracy_orientation = _deserializer.float32(buffer, bufferOffset);
    // Deserialize message field [timeout]
    data.timeout = _deserializer.float32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += std_msgs.msg.Header.getMessageSize(object.header);
    return length + 40;
  }

  static datatype() {
    // Returns string type for a message object
    return 'asctec_hl_comm/WaypointGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '507ec257de0ab6b6c1abb2c69409fbd5';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #goal
    Header header
    geometry_msgs/Point32   goal_pos
    float32                 goal_yaw
    geometry_msgs/Point32   max_speed
    float32 				accuracy_position        # determines the radius around the goal within the goal is considered as reached
    float32                 accuracy_orientation     # determines the range within the goal orientation is considered as reached, for the heli only yaw
    float32                 timeout                  # timeout in [s] after which flying to the waypoint stops
    
    ================================================================================
    MSG: std_msgs/Header
    # Standard metadata for higher-level stamped data types.
    # This is generally used to communicate timestamped data 
    # in a particular coordinate frame.
    # 
    # sequence ID: consecutively increasing ID 
    uint32 seq
    #Two-integer timestamp that is expressed as:
    # * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
    # * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
    # time-handling sugar is provided by the client library
    time stamp
    #Frame this data is associated with
    # 0: no frame
    # 1: global frame
    string frame_id
    
    ================================================================================
    MSG: geometry_msgs/Point32
    # This contains the position of a point in free space(with 32 bits of precision).
    # It is recommeded to use Point wherever possible instead of Point32.  
    # 
    # This recommendation is to promote interoperability.  
    #
    # This message is designed to take up less space when sending
    # lots of points at once, as in the case of a PointCloud.  
    
    float32 x
    float32 y
    float32 z
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new WaypointGoal(null);
    if (msg.header !== undefined) {
      resolved.header = std_msgs.msg.Header.Resolve(msg.header)
    }
    else {
      resolved.header = new std_msgs.msg.Header()
    }

    if (msg.goal_pos !== undefined) {
      resolved.goal_pos = geometry_msgs.msg.Point32.Resolve(msg.goal_pos)
    }
    else {
      resolved.goal_pos = new geometry_msgs.msg.Point32()
    }

    if (msg.goal_yaw !== undefined) {
      resolved.goal_yaw = msg.goal_yaw;
    }
    else {
      resolved.goal_yaw = 0.0
    }

    if (msg.max_speed !== undefined) {
      resolved.max_speed = geometry_msgs.msg.Point32.Resolve(msg.max_speed)
    }
    else {
      resolved.max_speed = new geometry_msgs.msg.Point32()
    }

    if (msg.accuracy_position !== undefined) {
      resolved.accuracy_position = msg.accuracy_position;
    }
    else {
      resolved.accuracy_position = 0.0
    }

    if (msg.accuracy_orientation !== undefined) {
      resolved.accuracy_orientation = msg.accuracy_orientation;
    }
    else {
      resolved.accuracy_orientation = 0.0
    }

    if (msg.timeout !== undefined) {
      resolved.timeout = msg.timeout;
    }
    else {
      resolved.timeout = 0.0
    }

    return resolved;
    }
};

module.exports = WaypointGoal;
