// Generated by gencpp from file asctec_hl_comm/mav_ctrl_motors.msg
// DO NOT EDIT!


#ifndef ASCTEC_HL_COMM_MESSAGE_MAV_CTRL_MOTORS_H
#define ASCTEC_HL_COMM_MESSAGE_MAV_CTRL_MOTORS_H

#include <ros/service_traits.h>


#include <asctec_hl_comm/mav_ctrl_motorsRequest.h>
#include <asctec_hl_comm/mav_ctrl_motorsResponse.h>


namespace asctec_hl_comm
{

struct mav_ctrl_motors
{

typedef mav_ctrl_motorsRequest Request;
typedef mav_ctrl_motorsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct mav_ctrl_motors
} // namespace asctec_hl_comm


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::asctec_hl_comm::mav_ctrl_motors > {
  static const char* value()
  {
    return "e005c4128d496dadc787b05eb5384496";
  }

  static const char* value(const ::asctec_hl_comm::mav_ctrl_motors&) { return value(); }
};

template<>
struct DataType< ::asctec_hl_comm::mav_ctrl_motors > {
  static const char* value()
  {
    return "asctec_hl_comm/mav_ctrl_motors";
  }

  static const char* value(const ::asctec_hl_comm::mav_ctrl_motors&) { return value(); }
};


// service_traits::MD5Sum< ::asctec_hl_comm::mav_ctrl_motorsRequest> should match 
// service_traits::MD5Sum< ::asctec_hl_comm::mav_ctrl_motors > 
template<>
struct MD5Sum< ::asctec_hl_comm::mav_ctrl_motorsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::asctec_hl_comm::mav_ctrl_motors >::value();
  }
  static const char* value(const ::asctec_hl_comm::mav_ctrl_motorsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::asctec_hl_comm::mav_ctrl_motorsRequest> should match 
// service_traits::DataType< ::asctec_hl_comm::mav_ctrl_motors > 
template<>
struct DataType< ::asctec_hl_comm::mav_ctrl_motorsRequest>
{
  static const char* value()
  {
    return DataType< ::asctec_hl_comm::mav_ctrl_motors >::value();
  }
  static const char* value(const ::asctec_hl_comm::mav_ctrl_motorsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::asctec_hl_comm::mav_ctrl_motorsResponse> should match 
// service_traits::MD5Sum< ::asctec_hl_comm::mav_ctrl_motors > 
template<>
struct MD5Sum< ::asctec_hl_comm::mav_ctrl_motorsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::asctec_hl_comm::mav_ctrl_motors >::value();
  }
  static const char* value(const ::asctec_hl_comm::mav_ctrl_motorsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::asctec_hl_comm::mav_ctrl_motorsResponse> should match 
// service_traits::DataType< ::asctec_hl_comm::mav_ctrl_motors > 
template<>
struct DataType< ::asctec_hl_comm::mav_ctrl_motorsResponse>
{
  static const char* value()
  {
    return DataType< ::asctec_hl_comm::mav_ctrl_motors >::value();
  }
  static const char* value(const ::asctec_hl_comm::mav_ctrl_motorsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ASCTEC_HL_COMM_MESSAGE_MAV_CTRL_MOTORS_H
