// Generated by gencpp from file asctec_hl_comm/mav_ctrl_motorsRequest.msg
// DO NOT EDIT!


#ifndef ASCTEC_HL_COMM_MESSAGE_MAV_CTRL_MOTORSREQUEST_H
#define ASCTEC_HL_COMM_MESSAGE_MAV_CTRL_MOTORSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace asctec_hl_comm
{
template <class ContainerAllocator>
struct mav_ctrl_motorsRequest_
{
  typedef mav_ctrl_motorsRequest_<ContainerAllocator> Type;

  mav_ctrl_motorsRequest_()
    : startMotors(false)  {
    }
  mav_ctrl_motorsRequest_(const ContainerAllocator& _alloc)
    : startMotors(false)  {
  (void)_alloc;
    }



   typedef uint8_t _startMotors_type;
  _startMotors_type startMotors;





  typedef boost::shared_ptr< ::asctec_hl_comm::mav_ctrl_motorsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::asctec_hl_comm::mav_ctrl_motorsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct mav_ctrl_motorsRequest_

typedef ::asctec_hl_comm::mav_ctrl_motorsRequest_<std::allocator<void> > mav_ctrl_motorsRequest;

typedef boost::shared_ptr< ::asctec_hl_comm::mav_ctrl_motorsRequest > mav_ctrl_motorsRequestPtr;
typedef boost::shared_ptr< ::asctec_hl_comm::mav_ctrl_motorsRequest const> mav_ctrl_motorsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::asctec_hl_comm::mav_ctrl_motorsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::asctec_hl_comm::mav_ctrl_motorsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace asctec_hl_comm

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'asctec_hl_comm': ['/home/mourams/hexv_ctl/src/asctec_mav_framework/asctec_hl_comm/msg', '/home/mourams/hexv_ctl/devel/share/asctec_hl_comm/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::asctec_hl_comm::mav_ctrl_motorsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::asctec_hl_comm::mav_ctrl_motorsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::asctec_hl_comm::mav_ctrl_motorsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::asctec_hl_comm::mav_ctrl_motorsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::asctec_hl_comm::mav_ctrl_motorsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::asctec_hl_comm::mav_ctrl_motorsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::asctec_hl_comm::mav_ctrl_motorsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6076998c2a5ec9144368e0457caa79ef";
  }

  static const char* value(const ::asctec_hl_comm::mav_ctrl_motorsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6076998c2a5ec914ULL;
  static const uint64_t static_value2 = 0x4368e0457caa79efULL;
};

template<class ContainerAllocator>
struct DataType< ::asctec_hl_comm::mav_ctrl_motorsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "asctec_hl_comm/mav_ctrl_motorsRequest";
  }

  static const char* value(const ::asctec_hl_comm::mav_ctrl_motorsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::asctec_hl_comm::mav_ctrl_motorsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool      startMotors\n\
";
  }

  static const char* value(const ::asctec_hl_comm::mav_ctrl_motorsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::asctec_hl_comm::mav_ctrl_motorsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.startMotors);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct mav_ctrl_motorsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::asctec_hl_comm::mav_ctrl_motorsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::asctec_hl_comm::mav_ctrl_motorsRequest_<ContainerAllocator>& v)
  {
    s << indent << "startMotors: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.startMotors);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASCTEC_HL_COMM_MESSAGE_MAV_CTRL_MOTORSREQUEST_H
