(cl:defpackage asctec_hl_comm-srv
  (:use )
  (:export
   "MAVCTRLSRV"
   "<MAVCTRLSRV-REQUEST>"
   "MAVCTRLSRV-REQUEST"
   "<MAVCTRLSRV-RESPONSE>"
   "MAVCTRLSRV-RESPONSE"
   "WGS84TOENU"
   "<WGS84TOENU-REQUEST>"
   "WGS84TOENU-REQUEST"
   "<WGS84TOENU-RESPONSE>"
   "WGS84TOENU-RESPONSE"
   "MAV_CTRL_MOTORS"
   "<MAV_CTRL_MOTORS-REQUEST>"
   "MAV_CTRL_MOTORS-REQUEST"
   "<MAV_CTRL_MOTORS-RESPONSE>"
   "MAV_CTRL_MOTORS-RESPONSE"
  ))

