// Generated by gencpp from file asctec_hl_comm/mav_ctrl.msg
// DO NOT EDIT!


#ifndef ASCTEC_HL_COMM_MESSAGE_MAV_CTRL_H
#define ASCTEC_HL_COMM_MESSAGE_MAV_CTRL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace asctec_hl_comm
{
template <class ContainerAllocator>
struct mav_ctrl_
{
  typedef mav_ctrl_<ContainerAllocator> Type;

  mav_ctrl_()
    : header()
    , type(0)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , yaw(0.0)
    , v_max_xy(0.0)
    , v_max_z(0.0)  {
    }
  mav_ctrl_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , type(0)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , yaw(0.0)
    , v_max_xy(0.0)
    , v_max_z(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int8_t _type_type;
  _type_type type;

   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;

   typedef float _yaw_type;
  _yaw_type yaw;

   typedef float _v_max_xy_type;
  _v_max_xy_type v_max_xy;

   typedef float _v_max_z_type;
  _v_max_z_type v_max_z;



  enum {
    acceleration = 1,
    velocity = 2,
    position = 3,
    velocity_body = 4,
    position_body = 5,
  };


  typedef boost::shared_ptr< ::asctec_hl_comm::mav_ctrl_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::asctec_hl_comm::mav_ctrl_<ContainerAllocator> const> ConstPtr;

}; // struct mav_ctrl_

typedef ::asctec_hl_comm::mav_ctrl_<std::allocator<void> > mav_ctrl;

typedef boost::shared_ptr< ::asctec_hl_comm::mav_ctrl > mav_ctrlPtr;
typedef boost::shared_ptr< ::asctec_hl_comm::mav_ctrl const> mav_ctrlConstPtr;

// constants requiring out of line definition

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::asctec_hl_comm::mav_ctrl_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::asctec_hl_comm::mav_ctrl_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace asctec_hl_comm

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'asctec_hl_comm': ['/home/mourams/hexv_ctl/src/asctec_mav_framework/asctec_hl_comm/msg', '/home/mourams/hexv_ctl/devel/share/asctec_hl_comm/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::asctec_hl_comm::mav_ctrl_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::asctec_hl_comm::mav_ctrl_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::asctec_hl_comm::mav_ctrl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::asctec_hl_comm::mav_ctrl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::asctec_hl_comm::mav_ctrl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::asctec_hl_comm::mav_ctrl_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::asctec_hl_comm::mav_ctrl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "845e0a830a06ad942cc0b1907c31bc38";
  }

  static const char* value(const ::asctec_hl_comm::mav_ctrl_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x845e0a830a06ad94ULL;
  static const uint64_t static_value2 = 0x2cc0b1907c31bc38ULL;
};

template<class ContainerAllocator>
struct DataType< ::asctec_hl_comm::mav_ctrl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "asctec_hl_comm/mav_ctrl";
  }

  static const char* value(const ::asctec_hl_comm::mav_ctrl_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::asctec_hl_comm::mav_ctrl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
int8        type        #message type\n\
\n\
# control commands, all units in SI units !!!\n\
# There are 3 operating modes of the helicopter:\n\
# 1. Acceleration: x, y, z correspond to x_dotdot etc... with the exception that yaw is angular velocity\n\
#    Inputs must be in body-coordinates\n\
#    Currently x~pitch, y~roll, z~thrust, units in rad and rad/s for yaw\n\
# 2. Velocity: x, y, z, yaw correspond to x_dot etc...\n\
#    Vehicle must have it's own pose estimation e.g. vision/GPS\n\
#    Inputs must be in body-coordinates\n\
#    Units in m/s and rad/s respectively\n\
# 3. Position\n\
#    Vehicle must have it's own pose estimation e.g. vision/GPS\n\
#    Inputs in fixed coordinate system\n\
#    v_max_* is only valid for this mode and limits the velocity a vehicle approaches the waypoint\n\
\n\
float32     x\n\
float32     y\n\
float32     z\n\
float32     yaw\n\
float32     v_max_xy\n\
float32     v_max_z\n\
\n\
int8 acceleration = 1\n\
int8 velocity = 2\n\
int8 position = 3\n\
int8 velocity_body = 4\n\
int8 position_body = 5\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::asctec_hl_comm::mav_ctrl_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::asctec_hl_comm::mav_ctrl_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.type);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.yaw);
      stream.next(m.v_max_xy);
      stream.next(m.v_max_z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct mav_ctrl_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::asctec_hl_comm::mav_ctrl_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::asctec_hl_comm::mav_ctrl_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "type: ";
    Printer<int8_t>::stream(s, indent + "  ", v.type);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
    s << indent << "v_max_xy: ";
    Printer<float>::stream(s, indent + "  ", v.v_max_xy);
    s << indent << "v_max_z: ";
    Printer<float>::stream(s, indent + "  ", v.v_max_z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASCTEC_HL_COMM_MESSAGE_MAV_CTRL_H
