// Generated by gencpp from file asctec_hl_comm/Wgs84ToEnu.msg
// DO NOT EDIT!


#ifndef ASCTEC_HL_COMM_MESSAGE_WGS84TOENU_H
#define ASCTEC_HL_COMM_MESSAGE_WGS84TOENU_H

#include <ros/service_traits.h>


#include <asctec_hl_comm/Wgs84ToEnuRequest.h>
#include <asctec_hl_comm/Wgs84ToEnuResponse.h>


namespace asctec_hl_comm
{

struct Wgs84ToEnu
{

typedef Wgs84ToEnuRequest Request;
typedef Wgs84ToEnuResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Wgs84ToEnu
} // namespace asctec_hl_comm


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::asctec_hl_comm::Wgs84ToEnu > {
  static const char* value()
  {
    return "b575b64084ce80473164a1c8719452c6";
  }

  static const char* value(const ::asctec_hl_comm::Wgs84ToEnu&) { return value(); }
};

template<>
struct DataType< ::asctec_hl_comm::Wgs84ToEnu > {
  static const char* value()
  {
    return "asctec_hl_comm/Wgs84ToEnu";
  }

  static const char* value(const ::asctec_hl_comm::Wgs84ToEnu&) { return value(); }
};


// service_traits::MD5Sum< ::asctec_hl_comm::Wgs84ToEnuRequest> should match 
// service_traits::MD5Sum< ::asctec_hl_comm::Wgs84ToEnu > 
template<>
struct MD5Sum< ::asctec_hl_comm::Wgs84ToEnuRequest>
{
  static const char* value()
  {
    return MD5Sum< ::asctec_hl_comm::Wgs84ToEnu >::value();
  }
  static const char* value(const ::asctec_hl_comm::Wgs84ToEnuRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::asctec_hl_comm::Wgs84ToEnuRequest> should match 
// service_traits::DataType< ::asctec_hl_comm::Wgs84ToEnu > 
template<>
struct DataType< ::asctec_hl_comm::Wgs84ToEnuRequest>
{
  static const char* value()
  {
    return DataType< ::asctec_hl_comm::Wgs84ToEnu >::value();
  }
  static const char* value(const ::asctec_hl_comm::Wgs84ToEnuRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::asctec_hl_comm::Wgs84ToEnuResponse> should match 
// service_traits::MD5Sum< ::asctec_hl_comm::Wgs84ToEnu > 
template<>
struct MD5Sum< ::asctec_hl_comm::Wgs84ToEnuResponse>
{
  static const char* value()
  {
    return MD5Sum< ::asctec_hl_comm::Wgs84ToEnu >::value();
  }
  static const char* value(const ::asctec_hl_comm::Wgs84ToEnuResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::asctec_hl_comm::Wgs84ToEnuResponse> should match 
// service_traits::DataType< ::asctec_hl_comm::Wgs84ToEnu > 
template<>
struct DataType< ::asctec_hl_comm::Wgs84ToEnuResponse>
{
  static const char* value()
  {
    return DataType< ::asctec_hl_comm::Wgs84ToEnu >::value();
  }
  static const char* value(const ::asctec_hl_comm::Wgs84ToEnuResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ASCTEC_HL_COMM_MESSAGE_WGS84TOENU_H
